spring.application.name=cursos
spring.datasource.url=jdbc:mysql://mysql:3306/cursos_db
spring.datasource.username=root
spring.datasource.password=2785030
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
logging.level.org.springframework.security=DEBUG

app.bucket-name=mibucketduocs3ccp

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://azureduocdcn.b2clogin.com/b5b7b5d9-c11a-4bd9-9e39-a4c98f2e83d4/v2.0/

