spring:
  application:
    name: cursos

  datasource:
    url: jdbc:mysql://localhost:3306/cursos_db
    username: root
    password: 2785030

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
      session-token:
    region:
      static: us-east-1

app:
  bucket-name: mibucketduocs3ccp
  h2:
    datasource:
      url: jdbc:h2:file:./data/resumen_compra_db
      username: sa
      password:
      driver-class-name: org.h2.Driver
